package vo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by chamin
 */
public class Notification  implements java.io.Serializable {


     private Integer notificationId;
     private Sensor sensor;
     private Date genaratedDate;
     private String message;
     private String priority;
     private Set destinations = new HashSet(0);

    public Notification() {
    }

	
    public Notification(Sensor sensor, Date genaratedDate, String message) {
        this.sensor = sensor;
        this.genaratedDate = genaratedDate;
        this.message = message;
    }
    public Notification(Sensor sensor, Date genaratedDate, String message, String priority, Set destinations) {
       this.sensor = sensor;
       this.genaratedDate = genaratedDate;
       this.message = message;
       this.priority = priority;
       this.destinations = destinations;
    }
   
    public Integer getNotificationId() {
        return this.notificationId;
    }
    
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }
    public Sensor getSensor() {
        return this.sensor;
    }
    
    public void setSensor(Sensor sensor) {
        this.sensor = sensor;
    }
    public Date getGenaratedDate() {
        return this.genaratedDate;
    }
    
    public void setGenaratedDate(Date genaratedDate) {
        this.genaratedDate = genaratedDate;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    public Set getDestinations() {
        return this.destinations;
    }
    
    public void setDestinations(Set destinations) {
        this.destinations = destinations;
    }




}


