package vo;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by chamin
 */
public class Notification  implements java.io.Serializable {


     private Integer notificationId; //auto incremented
     private String sensorId;
     private Date genaratedDate;
     private String message;
     private String priority;
     boolean seenByAdmin;
     boolean seenByMaintain;
     boolean read;
     boolean broken;
     
     //private Set destinations = new HashSet(0);

    public Notification() {
    }

    public Notification(Integer notificationId, String sensorId, Date genaratedDate, String message, String priority, boolean seenByAdmin, boolean seenByMaintain, boolean read,boolean broken) {
        this.notificationId = notificationId;
        this.sensorId = sensorId;
        this.genaratedDate = genaratedDate;
        this.message = message;
        this.priority = priority;
        this.seenByAdmin = seenByAdmin;
        this.seenByMaintain = seenByMaintain;
        this.read = read;
        this.broken=broken;
    }

	
    public Notification(String sensorId, Date genaratedDate, String message) {
        this.sensorId = sensorId;
        this.genaratedDate = genaratedDate;
        this.message = message;
    }
    public Notification(String sensorId, Date genaratedDate, String message, String priority) {
       this.sensorId = sensorId;
       this.genaratedDate = genaratedDate;
       this.message = message;
       this.priority = priority;
       
    }
    public Integer getNotificationId() {
        return this.notificationId;
    }
    
    public void setNotificationId(Integer notificationId) {
        this.notificationId = notificationId;
    }
    public String getSensorId() {
        return this.sensorId;
    }
    
    public void setSensor(String sensor) {
        this.sensorId = sensorId;
    }
    public Date getGenaratedDate() {
        return this.genaratedDate;
    }
    
    public void setGenaratedDate(Date genaratedDate) {
        this.genaratedDate = genaratedDate;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

    public boolean isSeenByAdmin() {
        return seenByAdmin;
    }

    public void setSeenByAdmin(boolean seenByAdmin) {
        this.seenByAdmin = seenByAdmin;
    }

    public boolean isSeenByMaintain() {
        return seenByMaintain;
    }

    public void setSeenByMaintain(boolean seenByMaintain) {
        this.seenByMaintain = seenByMaintain;
    }

    public boolean isRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }

    public boolean isBroken() {
        return broken;
    }

    public void setBroken(boolean broken) {
        this.broken = broken;
    }
    




}


